# https://aws.amazon.com/blogs/storage/persistent-storage-for-kubernetes/
# kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.7"
# sudo apt-get install -y nfs-common
# mkdir efs
# sudo mount -t nfs4 fs-0b73317285cf67838.efs.us-east-1.amazonaws.com:/ efs

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  fileSystemId: fs-0b73317285cf67838 # File system ID
