apiVersion: v1
kind: Service
metadata:
  name: webapp-color
  namespace: default
spec:
  selector:
    app: webapp-color
  type: NodePort
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30020