apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30020