# Service Load Balancer Work With Only Cloud Platform
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: Selector Label
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
