apiVersion: v1
kind: Service
metadata:
  name: daemonset-fluentbit-service
  namespace: default
spec:
  selector:
    name: fluentd-elasticsearch
  type: NodePort
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30011